### PR TITLE
fix: update chat format for Granite 3.0 model

### LINKED ISSUE #2065: Chat Bot AI app with lmstudio-community/granite-3.0 reiterates when input with response in the console output mutliple times
### Bug description

When sending an input into a prompt via browser, first input is processed correctly, but second question/input is kinda copied into answer prompt and seems like resend and appears iteratively in the output again and again. more questions make it worse.

Ref: https://github.com/containers/podman-desktop-extension-ai-lab/pull/2024

### Operating system

Mac OS 14

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

1. Install 1.3.2 AI Lab
2. Create podman Machine (Mac OS libkrun)
3. Start up chat bot app with mentioned model
4. Assert: app is up and running
5. In the App's details -> open the browser
6. Send an input and check for the output
7. Repeat step 6. 
8. Assert: LLM model answers as expected
Actual result: app/model responses multiple times like it is recycling the input over and over

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #2065

### What does this PR do?

Update Granite 3.0 model properties

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#2065 

### How to test this PR?

Run the chatbot recipe against this model

### CODE REVIEW

File: packages/backend/src/managers/application/applicationManager.ts [hunk 1]
```diff
@@ -202,6 +195,15 @@ export class ApplicationManager extends Publisher<ApplicationState[]> implements
       'model-id': model.id,
     });
 
+    // upload model to podman machine if user system is supported
+    if (!recipeComponents.inferenceServer) {
```
Comment (axel7083) [inline packages/backend/src/managers/application/applicationManager.ts:199]: why does adding the chat format need to change the code inside application manager ?

Comment (jeffmaury) [reply packages/backend/src/managers/application/applicationManager.ts:199]: Error on my side

**Review by axel7083 — APPROVED** [review]
