### PR TITLE
fix: forbid creating several playgrounds with the same name

### LINKED ISSUE #782: It is possible to create 2 playgrounds with the same name
The user can create a playground by specifying a name already used by another playground

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Raise an error when the user creates a playground with a name already used by another playground.

### Screenshot / video of UI

https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/1133d8b7-ce81-4e61-a96a-e6752e9a956f

### What issues does this PR fix or reference?

Fix #782 

### How to test this PR?

- Create a first playground
- try to create a second playground with the same name

### CODE REVIEW

File: packages/backend/src/managers/playgroundV2Manager.ts [hunk 1]
```diff
@@ -312,6 +315,11 @@ export class PlaygroundV2Manager implements Disposable {
     return name;
   }
 
+  private isFreeName(name: string): boolean {
+    const names = new Set(this.getConversations().map(c => c.name));
+    return !names.has(name);
+  }
```
Comment (axel7083) [inline packages/backend/src/managers/playgroundV2Manager.ts:321]:
```suggestion
  private isFreeName(name: string): boolean {
    return !this.getConversations().some(c => c.name === name)
  }
```

I do not think you need to use a `Set` here

**Review by axel7083 — COMMENTED** [review]
I have a weird feeling with `isFreeName` I am not a native english speaker, but I feel like `isNameFree` sound better

**Review by axel7083 — APPROVED** [review]
LGTM 🚀 ! Thanks for the changes!
