### PR TITLE
fix: open recipe in the right folder

### LINKED ISSUE #816: Open in VSCode should open the new "recipes" directory of ai-lab-recipes
AI Lab Recipes ships a new "recipes" directory with source for the respective use case (e.g., ChatBot).  To support the e2e user experience, it would be helpful to open the specific directory in VSCode as displayed in the screenshot below:

Screenshot 2024-04-04 at 11 45 40

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #816

### What does this PR do?

Change the recipe Open in VSCode to open in the right folder instead of the root Git repository

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

#816

### How to test this PR?

1. Pull a recipe
2. Open the recipe in VSCode

### CODE REVIEW

File: packages/backend/src/managers/applicationManager.ts [hunk 1]
```diff
@@ -131,6 +131,7 @@ export class ApplicationManager extends Publisher<ApplicationState[]> implements
 
       this.localRepositories.register({
         path: gitCloneInfo.targetDirectory,
+        sourcepath: path.join(gitCloneInfo.targetDirectory, recipe.basedir ?? ''),
```
Comment (benoitf) [inline packages/backend/src/managers/applicationManager.ts:134]:
```suggestion
        sourcePath: path.join(gitCloneInfo.targetDirectory, recipe.basedir ?? ''),
```

File: packages/backend/src/registries/LocalRepositoryRegistry.spec.ts [hunk 2]
```diff
@@ -68,10 +68,10 @@ test('should notify webview when register', () => {
     } as unknown as Webview,
     '/appUserDirectory',
   );
-  localRepositories.register({ path: 'random', labels: { 'recipe-id': 'random' } });
+  localRepositories.register({ path: 'random', sourcepath: 'random', labels: { 'recipe-id': 'random' } });
```
Comment (benoitf) [inline packages/backend/src/registries/LocalRepositoryRegistry.spec.ts:71]:
```suggestion
  localRepositories.register({ path: 'random', sourcePath: 'random', labels: { 'recipe-id': 'random' } });
```

File: packages/backend/src/registries/LocalRepositoryRegistry.spec.ts [hunk 3]
```diff
@@ -68,10 +68,10 @@ test('should notify webview when register', () => {
...
   expect(mocks.postMessageMock).toHaveBeenNthCalledWith(1, {
     id: Messages.MSG_LOCAL_REPOSITORY_UPDATE,
-    body: [{ path: 'random', labels: { 'recipe-id': 'random' } }],
+    body: [{ path: 'random', sourcepath: 'random', labels: { 'recipe-id': 'random' } }],
```
Comment (benoitf) [inline packages/backend/src/registries/LocalRepositoryRegistry.spec.ts:74]:
```suggestion
    body: [{ path: 'random', sourcePath: 'random', labels: { 'recipe-id': 'random' } }],
```

File: packages/backend/src/registries/LocalRepositoryRegistry.spec.ts [hunk 4]
```diff
@@ -83,7 +83,7 @@ test('should notify webview when unregister', async () => {
     '/appUserDirectory',
   );
   vi.spyOn(fs.promises, 'rm').mockResolvedValue();
-  localRepositories.register({ path: 'random', labels: { 'recipe-id': 'random' } });
+  localRepositories.register({ path: 'random', sourcepath: 'random', labels: { 'recipe-id': 'random' } });
```
Comment (benoitf) [inline packages/backend/src/registries/LocalRepositoryRegistry.spec.ts:86]:
```suggestion
  localRepositories.register({ path: 'random', sourcePath: 'random', labels: { 'recipe-id': 'random' } });
```

File: packages/backend/src/registries/LocalRepositoryRegistry.spec.ts [hunk 5]
```diff
@@ -107,8 +107,10 @@ test('should register localRepo if it find the folder of the recipe', () => {
     } as unknown as Recipe,
   ]);
 
+  const folder = path.join('/appUserDirectory', 'recipe');
   expect(registerMock).toHaveBeenCalledWith({
-    path: path.join('/appUserDirectory', 'recipe'),
+    path: folder,
+    sourcepath: folder,
```
Comment (benoitf) [inline packages/backend/src/registries/LocalRepositoryRegistry.spec.ts:113]:
```suggestion
    sourcePath: folder,
```

File: packages/backend/src/registries/LocalRepositoryRegistry.ts [hunk 6]
```diff
@@ -71,6 +71,7 @@ export class LocalRepositoryRegistry extends Publisher<LocalRepository[]> {
       if (fs.existsSync(recipeFolder)) {
         this.register({
           path: recipeFolder,
+          sourcepath: path.join(recipeFolder, recipe.basedir ?? ''),
```
Comment (benoitf) [inline packages/backend/src/registries/LocalRepositoryRegistry.ts:74]:
```suggestion
          sourcePath: path.join(recipeFolder, recipe.basedir ?? ''),
```

File: packages/frontend/src/lib/RecipeDetails.svelte [hunk 7]
```diff
@@ -48,7 +48,7 @@ const onClickRepository = () => {
 
 const openVSCode = () => {
   if (localPath) {
-    studioClient.openVSCode(localPath.path);
+    studioClient.openVSCode(localPath.sourcepath);
```
Comment (benoitf) [inline packages/frontend/src/lib/RecipeDetails.svelte:51]:
```suggestion
    studioClient.openVSCode(localPath.sourcePath);
```

File: packages/shared/src/models/ILocalRepository.ts [hunk 8]
```diff
@@ -1,4 +1,5 @@
 export interface LocalRepository {
   path: string;
+  sourcepath: string;
```
Comment (benoitf) [inline packages/shared/src/models/ILocalRepository.ts:3]:
```suggestion
  sourcePath: string;
```

**Review by benoitf — APPROVED** [review]

**Review by vrothberg — APPROVED** [review]
